### ISSUE TITLE
Please upload a zipped app for Windows

### ISSUE THREAD

**Issue by funkyfuture** [telota/quick-csr#12]
Since i eventually bumped the version, i had to create a new release here. Please build an archive from the current master's HEAD and add it to [this release](https://github.com/telota/quick-csr/releases/tag/v0.2).

btw, `x86-64` is Intel's name for the `amd64` architecture they got licensed from AMD. `x64` is no thing at all.

**Comment by lpodl** [comment]
I added an up-to-date release.

Allthough I understand how x86-64 is an appropriate name for a 64 processor architecture based on the x86 architecture, lets not confuse our average user too much.
x64 is a common name  as well (Wikipedia said so!: https://en.wikipedia.org/wiki/X86-64) and most windows users know: I am using a 64-bit version of windows. And hey, there's an "intel inside" sticker on my PC.
Lets avoid a possible "why does this say amd? / x86-64?" :smile:

**Comment by funkyfuture** [comment]
`x64` is plain wrong though maybe common. there's no such thing as a "a 64 processor architecture". the architecture still bases on the `x86` arch but has 64bit registers.

i think `x86_64` as token fits well between the `-` separators in the archive names.

**Comment by lpodl** [comment]
Lets agree on that then.
