### ISSUE TITLE
Setup a release page here

### ISSUE THREAD

**Issue by funkyfuture** [telota/quick-csr#7]
as the instructions now propose to aquire Python ZIP Applications from the releases page here, that one needs to be filled with contents.

though there have been no code changes, i'd say the version should be bumped to `0.1.1` beforehand to reflect the updated documentation and distribution modalities.

@lpodl, wanna give it a shot?

as filename schema for the zip apps i propose: `quick-csr-<OS>-<arch>.pyz` with any token given in lower-case. examples:

- `quick-csr-win7-x86.pyz`
- `quick-csr-osx-amd64.pyz`
- `quick-csr-linux-armv7l.pyz`

**Comment by lpodl** [comment]
Version has been changed, still working on other releases as described in the other issue.

**Comment by lpodl** [comment]
First win7-x64 build has been released. Version number was adressed in hotfix patch.
